### ISSUE TITLE
It doesn't care about notify at all.

### ISSUE THREAD

**Issue by beckend** [asynchronics/async-event#3]
```rust
let event = Event::new();
event.wait_until(|| Some(true)).await;
println!("done");
```

This resolves, it doesn't wait for any notification.

**Comment by sbarral** [comment]
Yes, this is actually by design. It reflects the most commonly used pattern which you can see for instance in the documentation of `std::sync::condvar` where the waiting thread looks like:

```rust
// Wait for the thread to start up.
let (lock, cvar) = &*pair;
let mut started = lock.lock().unwrap();
while !*started {
    started = cvar.wait(started).unwrap();
}
```

The `event_listener` also uses this pattern in its main example:

```rust
// Wait until the flag is set.
loop {
    // Check the flag.
    if flag.load(Ordering::SeqCst) {
        break;
    }

    // Start listening for events.
    let mut listener = event.listen();

    // Check the flag again after creating the listener.
    if flag.load(Ordering::SeqCst) {
        break;
    }

    // Wait for a notification and continue the loop.
    listener.wait();
}
```

**Comment by beckend** [comment]
the event_listener waits until you notify.

**Comment by beckend** [comment]
It's fine if it's by design, but why don't I just

```rust
loop {
	if get_my_flag().await {
		break;
	}	
	tokio::task::yield_now().await;
}
```

**Comment by beckend** [comment]
I mean I didn't care about any notification to begin with right.

**Comment by beckend** [comment]
```rust
 let events = Event::new();

  let task = tokio::spawn({
    let listener = events.listen();
    async move {
      listener.await;
      println!("notified");
    }
  });

  // events.notify_additional(1);
  task.await?;
```

This task will never resolve, and that is how event listener works. And if I comment out the notification, it proceeds.

**Comment by sbarral** [comment]
Not sure what you mean, but `wait_until` is definitely a higher-level primitive that `listener.wait()` from the `event_listener` crate, it is meant to replace the whole loop given in the above example. Due to the way `async_event` is implemented, it isn't really possible to expose a `wait` method unfortunately, so I'd recommend using `event_listener` if you need such a low-level primitive.

**Comment by beckend** [comment]
It doesn't replace anything, it doesn't even care about any notification.

**Comment by beckend** [comment]
I would just busy loop until my flag is true or false by the looks of it.

**Comment by sbarral** [comment]
It waits for a notification if whatever you need is not available.
Please be mindful that this is something that I published for free, and only because someone asked me to do so as a favor.

**Comment by beckend** [comment]
I am not blaming you, but I am just stating that it's an event based library, which doesn't wait for any events.

**Comment by sbarral** [comment]
I am not sure where the misunderstanding is; it does exactly the same as this loop, which is given as an example usage of `event_listener` and is basically the same as the example for `condvar`:
```rust
// Wait until the flag is set.
loop {
    // Check the flag.
    if flag.load(Ordering::SeqCst) {
        break;
    }

    // Start listening for events.
    let mut listener = event.listen();

    // Check the flag again after creating the listener.
    if flag.load(Ordering::SeqCst) {
        break;
    }

    // Wait for a notification and continue the loop.
    listener.wait();
}
```

You can see that this loop will break immediately if the flag is set, without waiting for a notification. This may not be what you want, but this is how most people will use a condvar.

**Comment by beckend** [comment]
listener.wait();
waits for an event on each loop, I need to notify it to continue the loop.
See my first comment, if you did not understand what wait does.
